/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.InvitationStatus;
import io.swagger.model.Invitation;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-02-26T05:19:37.458Z")

@Api(value = "invitations", description = "the invitations API")
public interface InvitationsApi {

    @ApiOperation(value = "Cancel an invitation", nickname = "invitationsInvitationIdDelete", notes = "Cancel and invitation", tags={ "Event Invitations", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "invitation cancelled"),
        @ApiResponse(code = 404, message = "invalid invitation id.") })
    @RequestMapping(value = "/invitations/{invitationId}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> invitationsInvitationIdDelete(@ApiParam(value = "",required=true) @PathVariable("invitationId") String invitationId);


    @ApiOperation(value = "accept or reject an invitation", nickname = "invitationsInvitationIdPut", notes = "accept or reject an invitation", response = Invitation.class, tags={ "Event Invitations", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful invitation response", response = Invitation.class) })
    @RequestMapping(value = "/invitations/{invitationId}",
        method = RequestMethod.PUT)
    ResponseEntity<Invitation> invitationsInvitationIdPut(@ApiParam(value = "",required=true) @PathVariable("invitationId") String invitationId,@ApiParam(value = ""  )  @Valid @RequestBody InvitationStatus data);

}
